### ISSUE TITLE
Yagdra - Hostile to friendly units

### ISSUE THREAD

**Issue by OUsnakebyte** [jrtoman/SC2-Complete-Edition#2] opened 2016-08-07 19:00 UTC
Hello -

I'm really loving your SC2 Complete Edition - well done.  Have a few bug issues.  First couple will be about Yagdra.  This one - already mentioned - is that it kills friendly units.  More to come; one issue per post, per your request.

**Comment by jrtoman** [comment] 2016-08-10 16:59
Dupe of Issue #1

**Closed as completed** 2016-08-10 16:59 UTC
